[package]
name = "projekto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy"}
env_logger = "0.9.0"

[features]
dev = ["bevy/dynamic"]