[package]
name = "projekto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
env_logger = "0.9.0"
bracket-noise = "0.8.2"
serde = "1"
ron = "0.7.1"
bincode = "1.3.3"
futures-lite = "1.12.0"
lz4_flex = "0.9.3"
itertools = "0.10"

# Used by perf_counter
once_cell = { version = "1.8.0", optional = true }

# Used by inspector
# bevy-inspector-egui = { version = "0.11.0", optional = true }

[dev-dependencies]
rand = "0.8.4"

[features]
default = [
     "dev",
     "perf_counter",
     # "inspector"
     # "serde_ron",
     # "mem_alloc",
]

dev = ["bevy/dynamic"]
perf_counter = ["dep:once_cell"]
# inspector = ["dep:bevy-inspector-egui"]
mem_alloc = []
serde_ron = []

[profile.dev.package."*"]
opt-level = 3
